%%{init: {'theme': 'base', 'themeVariables': { 'fontSize': '14px', 'fontFamily': 'Arial, Helvetica, sans-serif', 'fontWeight': '600'}}}%%
graph LR
    C(Concise<br/>சுருக்கம்) --> L(Logical<br/>தர்க்கம்)
    L --> E(Explicit<br/>வெளிப்படை)
    E --> A(Adaptive<br/>ஏற்புடைமை)
    A --> R(Reflective<br/>பகர்தல்)
    
    style C fill:#B2DFDB,stroke:#00796B,stroke-width:2px,color:#333
    style L fill:#C5CAE9,stroke:#303F9F,stroke-width:2px,color:#333
    style E fill:#FFCCBC,stroke:#E64A19,stroke-width:2px,color:#333
    style A fill:#F0F4C3,stroke:#AFB42B,stroke-width:2px,color:#333
    style R fill:#D7CCC8,stroke:#5D4037,stroke-width:2px,color:#333
