%%{init: {'theme': 'base', 'themeVariables': { 'fontSize': '14px', 'fontFamily': 'Arial, Helvetica, sans-serif', 'fontWeight': '600'}}}%%
graph LR
    C(Character<br/>பாத்திரம்) --> R
    R(Request<br/>கோரிக்கை) --> E1
    E1(Examples<br/>உதாரணங்கள்) --> A
    A(Adjustments<br/>மாற்றங்கள்) --> T
    T(Type<br/>வகை) --> E2
    E2(Extras<br/>கூடுதல்)
    
    style C fill:#FFCDD2,stroke:#E53935,stroke-width:2px,color:#333
    style R fill:#F8BBD0,stroke:#D81B60,stroke-width:2px,color:#333
    style E1 fill:#E1BEE7,stroke:#8E24AA,stroke-width:2px,color:#333
    style A fill:#D1C4E9,stroke:#5E35B1,stroke-width:2px,color:#333
    style T fill:#C5CAE9,stroke:#3949AB,stroke-width:2px,color:#333
    style E2 fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,color:#333
